services:
  # Our database management system
  db:
    image: mariadb:11
    environment:
      MARIADB_USER: &dbuser event
      MARIADB_PASSWORD: &dbpass eventsecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname events
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mariadb_data:
