micronaut:
  application:
    name: paymentsMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://localhost:3309/payments
    username: payment
    password: paymentsecret
jpa:
  default:
    entity-scan:
      packages: com.event.management.payments.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
stripe:
  secret-key: "${environment.getProperty('STRIPE_SECRET_KEY')}"
kafka:
  enabled: false