micronaut:
  server:
    port: 8083
  application:
    name: paymentsMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
stripe:
  secret-key: "${environment.getProperty('STRIPE_SECRET_KEY')}"
kafka:
  enabled: false