micronaut:
  server:
    port: 8082
  application:
    name: analyticsMicroservice
datasources:
  default:
    url: jdbc:mariadb://localhost:3308/analytics
    username: analytics
    password: analyticssecret
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages:
        - com.event.management.analytics.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}