micronaut:
  application:
    name: notificationMicroservice
  email:
    enabled: true
    host: smtp.gmail.com
    port: 587
    username: just.for.testing.only.email@gmail.com
    password: clmrzzqjhepploxj
    properties:
      mail.smtp.auth: true
      mail.smtp.auth.enable: true
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://localhost:3309/notifications
    username: notification
    password: notificationsecret
jpa:
  default:
    entity-scan:
      packages:
        - com.event.management.notifications.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  enabled: false