micronaut:
  application:
    name: notificationMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://localhost:3309/notifications
    username: notification
    password: notificationssecret
jpa:
  default:
    entity-scan:
      packages:
        - com.event.management.notifications.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  enabled: false
